### ISSUE TITLE
路径规划算法耗时

### ISSUE THREAD

**Issue by Feng1909** [muziing/PythonAutomatedDriving#2]
请问路径规划算法处理一帧数据需要耗时多久呢

**Comment by muziing** [comment]
在北理工的大佬面前，我这个项目真是班门弄斧了[捂脸]

这个算法只是一个“玩具级”，只在 PanoSim 仿真平台上跑过，没有在实车（我校暂时没有无人方程式）上试过。耗时应该和硬件平台关系比较大吧。Python 本身的性能也可能成为瓶颈，用 C++ 改写可能会有所提高。

**Comment by Feng1909** [comment]
很厉害很厉害，相互学习٩(*´◒`*)۶
